import Layout from "@/src/components/Layout";
import MyVaultSection from "@/src/components/sections/home/MyVaultSection";
import OsmosisPools from "@/src/components/sections/home/OsmosisPools";
import RecommendedSection from "@/src/components/sections/home/RecommendedSection";
import TopPerformers from "@/src/components/sections/home/TopPerformers";
import TopVerifiedVaults from "@/src/components/sections/home/TopVerifiedVaults";
import { dunbar } from "@/src/utils/fonts";
import Head from "next/head";

export default function Home() {
	return (
		<>
			<Head>
				<title>Quasar</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout>
				<section className="flex items-center justify-between mt-16 mb-12">
					<h2
						className={` ${dunbar.className} text-xl sm:text-2xl md:text-4xl font-bold`}
					>
						Welcome back, Jerry
					</h2>
					<div className="flex items-center gap-3">
						<button
							className={`bg-white text-black rounded-full py-1 px-3 text-center font-bold ${dunbar.className}`}
						>
							Buy $QSR
						</button>
						<button
							className={`bg-white text-black rounded-full py-1 px-3 text-center font-bold ${dunbar.className}`}
						>
							Create Vault
						</button>
					</div>
				</section>
				<MyVaultSection />
				<OsmosisPools />
				<TopVerifiedVaults />
				<RecommendedSection />
				<TopPerformers />
			</Layout>
		</>
	);
}
